---
# Security hardening override - SerpBear/Node.js compatible version
# This file provides security hardening optimized for Next.js/Node.js applications
# Based on Docker Security Best Practices with LinuxServer.io S6 compatibility

services:
  serpbear:
    # IMPORTANT: Security restrictions relaxed for Node.js/Next.js compatibility
    #
    # REASON: LinuxServer.io S6 Overlay + Node.js applications have fundamental
    # incompatibilities with Docker security hardening features:
    # - no-new-privileges conflicts with S6 process management
    # - capability restrictions prevent S6 user switching
    # - seccomp profiles block Node.js syscalls
    # - tmpfs /run restrictions break S6 initialization
    #
    # TRADE-OFF: Functional LinuxServer.io container vs. maximum security hardening
    # Node.js applications in S6 environment require relaxed security to function

    # Only essential security features that don't break S6/Node.js compatibility:

    # Resource limits for security and stability
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
          pids: 200
        reservations:
          cpus: '0.25'
          memory: 128M

    # tmpfs mounts for security (Node.js compatible)
    # /run excluded for S6 overlay compatibility
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
      - /var/tmp:rw,noexec,nosuid,size=50m
      # /run excluded: S6 overlay requires full control for process management

    # Enhanced logging for security monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=serpbear,environment=development"

    # Additional security environment variables
    environment:
      # Security hardening
      - UMASK=027                    # Restrictive file permissions
      - CORE_DUMP_SIZE=0            # Disable core dumps
      - DNS=1.1.1.1,8.8.8.8        # Secure DNS servers

      # Audit and monitoring
      - AUDIT_ENABLED=true          # Enable audit logging
      - DEBUG_MODE=false            # Disable debug mode for security

    # Additional volume security options
    volumes:
      # Override config volume with additional security
      - ${CONFIG_PATH:-./config}:/config:rw,Z
      - ${DATA_PATH:-./data}:/data:rw,Z
      - ${LOGS_PATH:-./logs}:/config/logs:rw,Z