#!/usr/bin/with-contenv bash
# shellcheck shell=bash

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "
-------------------------------------
User UID:    $(id -u abc)
User GID:    $(id -g abc)
-------------------------------------
"

# Display custom branding if branding file exists
if [[ -f /etc/s6-overlay/s6-rc.d/init-adduser/branding ]]; then
    cat /etc/s6-overlay/s6-rc.d/init-adduser/branding
fi