name: Bug report
description: Report a reproducible problem
title: "[BUG] <title>"
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
    validations:
      required: true
